//! Sound id ↔ playable-path resolution and the run-completion resolver.
//!
//! Two concerns, both pure (no IO except the caller supplying already-resolved
//! base directories), so they are unit-testable without a running app:
//!   - map a `SoundId` (a `"builtin:*"` key or a custom-sound uuid) to the file
//!     that should be played;
//!   - given a run's outcome, the entity's per-entity config, and the global
//!     settings, decide WHICH sound (if any) plays — the single shared
//!     `resolve_outcome_sound` used by every trigger point.

use std::path::PathBuf;

use crate::storage::sound::{
    EntitySoundConfig, SoundDescriptor, SoundKind, SoundOutcomeConfig, SoundSettings,
};

/// Prefix marking a built-in tone id. The suffix is the file stem under the
/// bundled `sounds/` resource dir (e.g. `builtin:success` → `sounds/success.wav`).
pub const BUILTIN_PREFIX: &str = "builtin:";

/// The built-in tone stems bundled as resources (generated by
/// `examples/gen_sounds.rs`). `success`/`error` are the default cues;
/// `chime`/`buzz` are extra options. Kept in sync with the committed
/// `sounds/*.wav` assets and the generator's `TONES` table.
pub const BUILTIN_STEMS: &[&str] = &["success", "error", "chime", "buzz"];

/// Whether `id` is a built-in tone id, returning its file stem when so.
fn builtin_stem(id: &str) -> Option<&str> {
    id.strip_prefix(BUILTIN_PREFIX)
        .filter(|stem| BUILTIN_STEMS.contains(stem))
}

/// The outcome a run finished with. Chosen by the trigger sites from the
/// executor / launch / scheduler terminal status.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Outcome {
    Success,
    Error,
}

/// Build the descriptor list for the built-in tones. The `label` is the raw
/// stem (the frontend localises built-in labels by id); custom sounds are
/// appended by the caller from the `custom_sounds` table.
pub fn builtin_descriptors() -> Vec<SoundDescriptor> {
    BUILTIN_STEMS
        .iter()
        .map(|stem| SoundDescriptor {
            id: format!("{BUILTIN_PREFIX}{stem}"),
            label: (*stem).to_string(),
            kind: SoundKind::Builtin,
        })
        .collect()
}

/// Resolve a `SoundId` to the file to play, given the two base directories:
/// `resource_dir` for bundled built-ins (`<resource>/sounds/<stem>.wav`) and
/// `custom_dir` for user uploads (`<custom>/<stored_filename>`).
///
/// `lookup_custom` maps a custom-sound id to its stored filename (the caller
/// supplies this from the `custom_sounds` table). Returns `None` for an
/// unknown id — a dangling reference degrades to silence rather than erroring.
pub fn resolve_path<F>(
    id: &str,
    resource_dir: &std::path::Path,
    custom_dir: &std::path::Path,
    lookup_custom: F,
) -> Option<PathBuf>
where
    F: FnOnce(&str) -> Option<String>,
{
    if let Some(stem) = builtin_stem(id) {
        return Some(resource_dir.join("sounds").join(format!("{stem}.wav")));
    }
    lookup_custom(id).map(|filename| custom_dir.join(filename))
}

/// Pick the outcome slot from an entity config.
fn outcome_slot(
    entity: Option<&EntitySoundConfig>,
    outcome: Outcome,
) -> Option<&SoundOutcomeConfig> {
    let cfg = entity?;
    match outcome {
        Outcome::Success => cfg.success.as_ref(),
        Outcome::Error => cfg.error.as_ref(),
    }
}

/// The global fallback sound id for an outcome.
fn global_sound_id(settings: &SoundSettings, outcome: Outcome) -> Option<String> {
    match outcome {
        Outcome::Success => settings.success_sound_id.clone(),
        Outcome::Error => settings.error_sound_id.clone(),
    }
}

/// Decide which sound id (if any) should play for a finished run.
///
/// Resolution contract (see docs/sound-notifications.md):
///   - A per-entity outcome slot that is PRESENT overrides the global default:
///       - `enabled: true`  → its `sound_id`, else the global sound for the
///         outcome. Plays even when the global master switch is off.
///       - `enabled: false` → silent (explicitly suppresses the global default).
///   - An ABSENT per-entity slot inherits the global default, which only plays
///     when the global master switch (`settings.enabled`) is on.
///
/// Returns the chosen `SoundId`, or `None` for silence. Path resolution and the
/// "does this id actually exist" check happen later in `resolve_path`; a
/// resolved-but-missing id there degrades to silence.
pub fn resolve_outcome_sound(
    entity: Option<&EntitySoundConfig>,
    settings: &SoundSettings,
    outcome: Outcome,
) -> Option<String> {
    match outcome_slot(entity, outcome) {
        // Per-entity slot present: it wins over the global default entirely.
        Some(slot) => {
            if !slot.enabled {
                return None; // explicit per-entity suppress
            }
            slot.sound_id
                .clone()
                .or_else(|| global_sound_id(settings, outcome))
        }
        // No per-entity slot: inherit the global default, gated on the master.
        None => {
            if !settings.enabled {
                return None;
            }
            global_sound_id(settings, outcome)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    fn settings(enabled: bool, success: Option<&str>, error: Option<&str>) -> SoundSettings {
        SoundSettings {
            enabled,
            success_sound_id: success.map(String::from),
            error_sound_id: error.map(String::from),
            volume: 0.8,
        }
    }

    fn slot(enabled: bool, sound: Option<&str>) -> SoundOutcomeConfig {
        SoundOutcomeConfig {
            enabled,
            sound_id: sound.map(String::from),
        }
    }

    #[test]
    fn builtin_stem_recognises_only_known_stems() {
        assert_eq!(builtin_stem("builtin:success"), Some("success"));
        assert_eq!(builtin_stem("builtin:buzz"), Some("buzz"));
        assert_eq!(builtin_stem("builtin:unknown"), None);
        assert_eq!(builtin_stem("custom-uuid"), None);
    }

    #[test]
    fn resolve_path_builtin_points_into_resource_sounds() {
        let p = resolve_path(
            "builtin:success",
            Path::new("/res"),
            Path::new("/data/sounds"),
            |_| None,
        );
        assert_eq!(p, Some(PathBuf::from("/res/sounds/success.wav")));
    }

    #[test]
    fn resolve_path_custom_joins_stored_filename() {
        let p = resolve_path(
            "uuid-1",
            Path::new("/res"),
            Path::new("/data/sounds"),
            |id| (id == "uuid-1").then(|| "uuid-1.mp3".to_string()),
        );
        assert_eq!(p, Some(PathBuf::from("/data/sounds/uuid-1.mp3")));
    }

    #[test]
    fn resolve_path_unknown_id_is_none() {
        let p = resolve_path("nope", Path::new("/res"), Path::new("/data"), |_| None);
        assert_eq!(p, None);
    }

    // ---- resolve_outcome_sound truth table ---------------------------------

    #[test]
    fn absent_slot_global_off_is_silent() {
        // The out-of-the-box default: nothing configured, global off → silent.
        let s = settings(false, Some("builtin:success"), Some("builtin:error"));
        assert_eq!(resolve_outcome_sound(None, &s, Outcome::Success), None);
        assert_eq!(resolve_outcome_sound(None, &s, Outcome::Error), None);
    }

    #[test]
    fn absent_slot_global_on_uses_global_sound() {
        let s = settings(true, Some("builtin:success"), Some("builtin:error"));
        assert_eq!(
            resolve_outcome_sound(None, &s, Outcome::Success),
            Some("builtin:success".into())
        );
        assert_eq!(
            resolve_outcome_sound(None, &s, Outcome::Error),
            Some("builtin:error".into())
        );
    }

    #[test]
    fn present_enabled_slot_plays_even_when_global_off() {
        // A per-entity enabled slot plays regardless of the master switch.
        let s = settings(false, Some("builtin:success"), None);
        let entity = EntitySoundConfig {
            success: Some(slot(true, Some("custom-1"))),
            error: None,
        };
        assert_eq!(
            resolve_outcome_sound(Some(&entity), &s, Outcome::Success),
            Some("custom-1".into())
        );
    }

    #[test]
    fn present_enabled_slot_without_sound_falls_back_to_global() {
        let s = settings(false, Some("builtin:success"), None);
        let entity = EntitySoundConfig {
            success: Some(slot(true, None)),
            error: None,
        };
        assert_eq!(
            resolve_outcome_sound(Some(&entity), &s, Outcome::Success),
            Some("builtin:success".into())
        );
    }

    #[test]
    fn present_disabled_slot_suppresses_global_default() {
        // Even with the global default set (and global on), an explicit
        // per-entity disable is silent.
        let s = settings(true, Some("builtin:success"), None);
        let entity = EntitySoundConfig {
            success: Some(slot(false, None)),
            error: None,
        };
        assert_eq!(
            resolve_outcome_sound(Some(&entity), &s, Outcome::Success),
            None
        );
    }

    #[test]
    fn other_outcome_is_independent() {
        // Configuring success must not affect the error outcome, which here
        // falls through to the (off) global → silent.
        let s = settings(false, None, None);
        let entity = EntitySoundConfig {
            success: Some(slot(true, Some("x"))),
            error: None,
        };
        assert_eq!(
            resolve_outcome_sound(Some(&entity), &s, Outcome::Success),
            Some("x".into())
        );
        assert_eq!(
            resolve_outcome_sound(Some(&entity), &s, Outcome::Error),
            None
        );
    }

    #[test]
    fn builtin_descriptors_cover_every_stem() {
        let d = builtin_descriptors();
        assert_eq!(d.len(), BUILTIN_STEMS.len());
        assert!(d.iter().all(|x| x.kind == SoundKind::Builtin));
        assert_eq!(d[0].id, "builtin:success");
    }
}
